CREATE TABLE IF NOT EXISTS bookstore.author
(
    id    bigint generated by default as identity
        primary key,
    age   integer not null,
    genre varchar(255),
    name  varchar(255)
);

CREATE TABLE IF NOT EXISTS bookstore.book
(
    id           bigint generated by default as identity
        primary key,
    isbn         varchar(255),
    title        varchar(255),
    publisher_id bigint
        constraint fk_book_publisher
            references publisher,
    author_id    bigint
        constraint fk_book_author
            references author
);

CREATE TABLE IF NOT EXISTS bookstore.publisher
(
    id      bigint generated by default as identity
        primary key,
    company varchar(255)
);

CREATE TABLE IF NOT EXISTS bookstore.author_book
(
    author_id    bigint,
    book_id    bigint
);